services:
  getfit:
    build:
      context: .
      dockerfile: Dockerfile
    image: fitnessapp-prodv1
    restart: unless-stopped
    container_name: fit-backend-service
    ports:
      - 8000:8000
    volumes:
      - ./secrets:/run/secrets:ro

